version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: analytics-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config:/etc/clickhouse-server/config.d
      - ./clickhouse-users:/etc/clickhouse-server/users.d
    networks:
      - analytics-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  analytics-service:
    build: .
    container_name: analytics-service
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      PORT: 3005
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DATABASE: analytics
      CORS_ORIGIN: http://localhost:3000
      JWT_SECRET: your_jwt_secret_key_here
      LOG_LEVEL: info
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - analytics-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  clickhouse_data:
    driver: local

networks:
  analytics-network:
    driver: bridge
