version: '3.8'

services:
  # MongoDB 資料庫 (商品服務專用)
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ecommerce-network

  # PostgreSQL 資料庫 (交易數據)
  postgresql:
    image: postgres:15-alpine
    container_name: ecommerce-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_transactions
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./scripts/postgres-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - ecommerce-network

  # Redis 快取資料庫 (階段3新增)
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass password123
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  # Milvus 向量資料庫 (階段3新增)
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - milvus_etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - ecommerce-network

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - milvus_minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - ecommerce-network

  milvus-standalone:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus-standalone
    restart: unless-stopped
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - milvus-etcd
      - milvus-minio
    networks:
      - ecommerce-network

  # ClickHouse 時間序列資料庫 (階段3新增)
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: ecommerce-clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: ecommerce_analytics
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9002:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/clickhouse-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - ecommerce-network

  # MinIO 文件存儲服務 (獨立服務)
  minio-files:
    image: minio/minio:latest
    container_name: ecommerce-minio-files
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: product-images,user-avatars,category-images,system-files
    ports:
      - "9010:9000"      # API 端口
      - "9011:9001"      # Console 端口
    volumes:
      - minio_files_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ecommerce-network

volumes:
  mongodb_data:
  postgresql_data:
  redis_data:
  milvus_etcd_data:
  milvus_minio_data:
  milvus_data:
  clickhouse_data:
  minio_files_data:

networks:
  ecommerce-network:
    driver: bridge
