version: '3.8'

services:
  # MinIO 對象存儲服務
  minio-files:
    image: minio/minio:latest
    container_name: ecommerce-minio-files
    ports:
      - "9000:9000"      # API 端口
      - "9001:9001"      # Console 端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: product-images,user-avatars,category-images,system-files
    volumes:
      - minio_data:/data
      - ./minio-config:/root/.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ecommerce-network

  # PostgreSQL 數據庫
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  # 系統服務
  system-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-system-service
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: production
      PORT: 3005
      
      # PostgreSQL 配置
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ecommerce_system
      DB_USER: postgres
      DB_PASSWORD: postgres123
      
      # MinIO 配置 (獨立文件存儲服務)
      MINIO_ENDPOINT: minio-files
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      
      # 存儲桶配置
      BUCKET_PRODUCTS: product-images
      BUCKET_AVATARS: user-avatars
      BUCKET_CATEGORIES: category-images
      BUCKET_SYSTEM: system-files
      
      # 圖片處理配置
      MAX_FILE_SIZE: 10485760  # 10MB
      ALLOWED_IMAGE_TYPES: image/jpeg,image/png,image/gif,image/webp
      IMAGE_QUALITY: 80
      THUMBNAIL_SIZE: 300
      
      # JWT 配置
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./exports:/app/exports
    depends_on:
      postgres:
        condition: service_healthy
      minio-files:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ecommerce-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
